export const PRODUCT_DATA_REQUEST = 'PRODUCT_DATA_REQUEST'
export const PRODUCT_DATA_SUCCESS = 'PRODUCT_DATA_SUCCESS'
export const PRODUCT_DATA_FAIL = 'PRODUCT_DATA_FAIL'

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST'
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS'
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL'